<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsDesomniaPlugin>true</IsDesomniaPlugin>
    <RootNamespace>MadWizard.Desomnia.Network.Traefik</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DesomniaCore\DesomniaCore.csproj" />
    <ProjectReference Include="..\..\modules\NetworkMonitor\NetworkMonitor.csproj" />
  </ItemGroup>

</Project>
