<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsDesomniaPlugin>true</IsDesomniaPlugin>
    <RootNamespace>MadWizard.Desomnia.Service.Bridge</RootNamespace>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestMessage.proto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\DesomniaService\DesomniaService.csproj" />
    <ProjectReference Include="..\DesomniaPipe\DesomniaPipe.csproj" />
  </ItemGroup>

</Project>
