using MadWizard.Desomnia.Configuration.Xml;
using Microsoft.Extensions.Logging;
using System.Xml.Linq;

namespace MadWizard.Desomnia.Environments.Export
{
    /// <summary>
    /// Writes the effective configuration as XML (indented, for legibility) to the
    /// <c>writeEffectiveXML</c> path — reconstructed from the abstract tree, so leaves keep
    /// the form they were written in (attribute vs. element), the format version declared as
    /// the root element's <c>version</c> attribute (the authoritative style, see
    /// <see cref="XConfigVersion"/>): the file is the result of a migration and is never
    /// migrated itself. The file is removed again when the application stops, and whenever
    /// the configured path changes or disappears.
    /// </summary>
    internal sealed class EffectiveXMLExporter(EnvironmentMonitor monitor) : EffectiveConfigurationExporter(monitor)
    {
        protected override void Export(EffectiveConfiguration effective)
        {
            lock (this) if (effective.Settings.WriteEffectiveXML is string path)
            {
                try
                {
                    XComment comment = 
                        new($" effective configuration [active environments: {effective.ActiveDescription}]" +
                            " - generated by Desomnia, removed on shutdown ");

                    XElement root = ConfigNodeXmlWriter.ToXElement(effective.Root);

                    root.SetAttributeValue(XConfigVersion.VERSION_ATTRIBUTE, effective.Settings.Version);

                    var document = new XDocument(new XDeclaration("1.0", "utf-8", null), comment, root);

                    document.Save(path);

                    WrittenPath = path;
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    Logger.LogWarning(ex, $"Failed to write the effective configuration to {path}");
                }
            }
        }
    }
}
