using Microsoft.Extensions.Logging;
using System.Text;

namespace MadWizard.Desomnia.Environments.Export
{
    /// <summary>
    /// Writes the effective configuration in the bare, flattened-out IConfiguration form —
    /// one <c>path:to:key=value</c> line per entry, in document order — to the
    /// <c>outputEffectiveConfiguration</c> path. This is the unambiguous export: exactly the
    /// keys and values the binder sees, with none of the XML form left. The file is removed
    /// again when the application stops.
    /// </summary>
    internal sealed class EffectiveKeyValueExporter(EnvironmentMonitor monitor) : EffectiveConfigurationExporter(monitor)
    {
        protected override void Export(EffectiveConfiguration effective)
        {
            lock (this) if (effective.Settings.OutputEffectiveConfiguration is string path)
            {
                try
                {
                    StringBuilder text = new();

                    text.AppendLine($"# effective configuration [active environments: {effective.ActiveDescription}]");
                    text.AppendLine($"# generated by Desomnia, removed on shutdown");

                    foreach (var (key, value) in effective.Data.Pairs)
                        text.AppendLine($"{key}={value}");

                    File.WriteAllText(path, text.ToString(), Encoding.UTF8);

                    WrittenPath = path;
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    Logger.LogWarning(ex, $"Failed to write the effective configuration to {path}");
                }
            }
        }
    }
}
