<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<LangVersion>preview</LangVersion>
	<TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>MadWizard.Desomnia.Service.Duo</RootNamespace>
	<SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
	<OutputType>Library</OutputType>
    <IsDesomniaPlugin>true</IsDesomniaPlugin>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tools\**" />
    <EmbeddedResource Remove="Tools\**" />
    <None Remove="Tools\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="13.1.0" />
    <PackageReference Include="WindowsFirewallHelper" Version="2.2.0.86" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DuoStreamIntegration.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DesomniaService\DesomniaService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
