<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsDesomniaPlugin>true</IsDesomniaPlugin>
    <RootNamespace>MadWizard.Desomnia.Network.HyperV</RootNamespace>
	<LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DesomniaService\DesomniaService.csproj" />
  </ItemGroup>

</Project>
